export const GET_LOCATIONDATA_REQUEST = "GET_LOCATIONDATA_REQUEST";
export const GET_LOCATIONDATA_SUCCESS = "GET_LOCATIONDATA_SUCCESS";
export const GET_LOCATIONDATA_FAILURE = "GET_LOCATIONDATA_FAILURE";
